openapi: 3.0.3
info:
  title: My App
  version: 1.0.0
tags:
  - name: Order
    description: "Order endpoints"
paths:
  /api/v0/order:
    post:
      tags:
        - Order
      summary: 'Create Order'
      operationId: createOrder
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        200:
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/SuccessMessage'
        400:
          description: Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
components:
  schemas:
    Order:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        type:
          type: string
    SuccessMessage:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    ErrorMessage:
      type: object
      properties:
        code:
          type: string
        message:
          type: array
          items:
            type: string